### ISSUE TITLE
Missing region in config

### ISSUE THREAD

**Issue by siddharth-teli** [near/near-contract-helper#633] opened 2022-06-29 08:05 UTC
Running contract helper locally with near core & wallet. When i create account from near wallet it throws `Missing region in config` . This error is thrown when `/account/seedPhraseAdded` is called  after `/account` from wallet. 
![Screenshot from 2022-06-29 13-29-19](https://user-images.githubusercontent.com/107669916/176384857-20c4ac84-9c11-4126-af6f-a4b708ccbc2f.png)

**Comment by siddharth-teli** [comment] 2022-06-30 06:09
@andy-haynes Thanks for replying, Can you give an ETA for local DynamoDB support. Also, as contract helper was using postgres before for storing recovery methods. Can you point to the commit which works well with postgres.

**Comment by andy-haynes** [comment] 2022-07-12 16:55
@siddharth-teli I don't have an ETA at the moment because this is pretty low priority work due to the fact that it does not hinder local development. As before I understand the error can be jarring but it doesn't really have any impact on wallet functionality unless you are testing recovery methods. When I have time I will clean up and push the feature branch implementing local DynamoDB, but in the meantime it should not be affecting your local development. Can you tell me how this error is affecting your local development other than you're seeing an error in the console?

> Can you point to the commit which works well with postgres.

This would put you months behind the current head of master and is very likely more trouble than it's worth. If you're running code that old we won't really be able to help you with issues that you encounter. If you insist on doing this anyway you can try using this hash: 2ee6c77f0bed2baab95571bb9d7af41bbf90f00d.

Closing this as another duplicate of #621

**Closed by andy-haynes** 2022-07-12 16:55 UTC
